/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.speed_liv.menu.api;

import com.speed_liv.menu.model.Plat;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-18T08:35:46.768096443Z[Etc/UTC]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "plats", description = "the plats API")
public interface PlatsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /plats : Liste tous les plats
     *
     * @return Liste des plats (status code 200)
     */
    @Operation(
        operationId = "getAllPlats",
        summary = "Liste tous les plats",
        responses = {
            @ApiResponse(responseCode = "200", description = "Liste des plats", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Plat.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/plats",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Plat>> getAllPlats(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"price\" : 6.027456183070403, \"name\" : \"name\", \"id\" : 0, \"disponible\" : true }, { \"price\" : 6.027456183070403, \"name\" : \"name\", \"id\" : 0, \"disponible\" : true } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /plats/{id} : Consulter un plat
     *
     * @param id  (required)
     * @return Détails du plat (status code 200)
     *         or Plat non trouvé (status code 404)
     */
    @Operation(
        operationId = "getPlatById",
        summary = "Consulter un plat",
        responses = {
            @ApiResponse(responseCode = "200", description = "Détails du plat", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Plat.class))
            }),
            @ApiResponse(responseCode = "404", description = "Plat non trouvé")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/plats/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Plat> getPlatById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"price\" : 6.027456183070403, \"name\" : \"name\", \"id\" : 0, \"disponible\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
